<template>
  <div class="loadingio-spinner-spinner-e3toiyw41xj">
    <div class="ldio-e794ogoqv0p">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
/* generated by https://loading.io/ */

@keyframes ldio-e794ogoqv0p {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-e794ogoqv0p div {
  left: 84.60000000000001px;
  top: 43.2px;
  position: absolute;
  animation: ldio-e794ogoqv0p linear 1s infinite;
  background: #353535;
  width: 10.8px;
  height: 21.6px;
  border-radius: 5.4px / 10.8px;
  transform-origin: 5.4px 46.800000000000004px;
}
.ldio-e794ogoqv0p div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #353535;
}
.ldio-e794ogoqv0p div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #353535;
}
.ldio-e794ogoqv0p div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #353535;
}
.ldio-e794ogoqv0p div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #353535;
}
.ldio-e794ogoqv0p div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #353535;
}
.ldio-e794ogoqv0p div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #353535;
}
.ldio-e794ogoqv0p div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #353535;
}
.ldio-e794ogoqv0p div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #353535;
}
.ldio-e794ogoqv0p div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #353535;
}
.ldio-e794ogoqv0p div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #353535;
}
.ldio-e794ogoqv0p div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #353535;
}
.ldio-e794ogoqv0p div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #353535;
}
.loadingio-spinner-spinner-e3toiyw41xj {
  width: 180px;
  height: 180px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-e794ogoqv0p {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-e794ogoqv0p div {
  box-sizing: content-box;
}
</style>
